# Build and publish the book online

name: build
on:
  push:
    branches: ["master"]
permissions:
  id-token: write

jobs:
  build-book:
    name: Build Jupyter-book
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build the book
        run: |
          jupyter-book build src

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: src/_build/html

      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
